In [1]:
%load_ext autoreload
%autoreload 2

In [88]:
%reload_ext autoreload

In [89]:
import pandas as pd
import numpy as np
import utils
import sys

In [90]:
from ui_widgets import AppUI
from api_worker import Worker

In [91]:
AppUI(worker=Worker())

Initializing LDA model and scores ...


AppUI(children=(VBox(children=(Label(value='Select way to choose your topics:'), ToggleButtons(options=('From Topics List', 'Write Description', 'Search DBPL'), value='From Topics List'), HBox(children=(Checkbox(value=False, description='Topic 0'), Checkbox(value=False, description='Topic 1'), Checkbox(value=False, description='Topic 2'), Checkbox(value=False, description='Topic 3'), Checkbox(value=False, description='Topic 4'), Checkbox(value=False, description='Topic 5'), Checkbox(value=False, description='Topic 6'), Checkbox(value=False, description='Topic 7'), Checkbox(value=False, description='Topic 8'), Checkbox(value=False, description='Topic 9'), Checkbox(value=False, description='Topic 10'), Checkbox(value=False, description='Topic 11'), Checkbox(value=False, description='Topic 12'), Checkbox(value=False, description='Topic 13'), Checkbox(value=False, description='Topic 14'), Checkbox(value=False, description='Topic 15'), Checkbox(value=False, description='Topic 16'), Checkbox(value=False, description='Topic 17'), Checkbox(value=False, description='Topic 18'), Checkbox(value=False, description='Topic 19'), Checkbox(value=False, description='Topic 20'), Checkbox(value=False, description='Topic 21'), Checkbox(value=False, description='Topic 22'), Checkbox(value=False, description='Topic 23'), Checkbox(value=False, description='Topic 24'), Checkbox(value=False, description='Topic 25'), Checkbox(value=False, description='Topic 26'), Checkbox(value=False, description='Topic 27'), Checkbox(value=False, description='Topic 28'), Checkbox(value=False, description='Topic 29'), Checkbox(value=False, description='Topic 30'), Checkbox(value=False, description='Topic 31'), Checkbox(value=False, description='Topic 32'), Checkbox(value=False, description='Topic 33'), Checkbox(value=False, description='Topic 34'), Checkbox(value=False, description='Topic 35'), Checkbox(value=False, description='Topic 36'), Checkbox(value=False, description='Topic 37'), Checkbox(value=False, description='Topic 38'), Checkbox(value=False, description='Topic 39'), Checkbox(value=False, description='Topic 40'), Checkbox(value=False, description='Topic 41'), Checkbox(value=False, description='Topic 42'), Checkbox(value=False, description='Topic 43'), Checkbox(value=False, description='Topic 44'), Checkbox(value=False, description='Topic 45'), Checkbox(value=False, description='Topic 46'), Checkbox(value=False, description='Topic 47'), Checkbox(value=False, description='Topic 48'), Checkbox(value=False, description='Topic 49')), layout=Layout(align_items='stretch', border='solid 2px', margin='3px', padding='2px', width='100%')), VBox(children=(Label(value='Choose Recommender:'), ToggleButtons(options=('Recommender 1', 'Recommender 2'), value='Recommender 1'), Label(value=''), Button(description='Make Mentor Recommendation', style=ButtonStyle()), HTML(value='')), layout=Layout(align_items='center', border='Solid 2px', display='flex', flex_flow='column', width='100%'))), layout=Layout(align_items='center', display='flex', justify_content='center', width='100%')),))

ValueError: shapes (51,) and (7288,51) not aligned: 51 (dim 0) != 7288 (dim 0)

In [93]:
movies_df = pd.read_csv('data/movie_emb.csv', sep = ',', 
                   encoding='utf-8', low_memory=False)
        
_mentee_emb = movies_df.as_matrix()

user_df = pd.read_csv('data/user_emb.csv', sep = ',', 
           encoding='utf-8', low_memory=False)

_mentor_emb = user_df.as_matrix()

In [110]:
_mentee_emb[7]
np.argsort(np.dot(_mentee_emb[1090], _mentor_emb.T))

array([   0,    1,    2, ..., 7285, 7286, 7287])

In [104]:
np.dot(_mentee_emb[1000], _mentor_emb.T)

array([-5.17100563e-04,  1.00000283e+03,  2.00000212e+03, ...,
        7.28500000e+06,  7.28600000e+06,  7.28700000e+06])

In [111]:
np.dot(_mentee_emb, _mentor_emb.T)

array([[ 9.77371056e-03,  7.24167011e-04, -7.88941165e-05, ...,
         5.45898464e-03, -2.57192891e-03,  5.45838168e-04],
       [ 5.61273742e-04,  9.96636186e-01,  1.99640005e+00, ...,
         7.28500026e+03,  7.28599918e+03,  7.28699604e+03],
       [-1.60147847e-03,  2.00131457e+00,  4.00164868e+00, ...,
         1.45699983e+04,  1.45720004e+04,  1.45740022e+04],
       ...,
       [ 1.12489269e-04,  1.40730015e+04,  2.81460008e+04, ...,
         1.02521805e+08,  1.02535878e+08,  1.02549951e+08],
       [-1.95625838e-33,  1.40740000e+04,  2.81480000e+04, ...,
         1.02529090e+08,  1.02543164e+08,  1.02557238e+08],
       [ 1.46748619e-03,  1.40750141e+04,  2.81500042e+04, ...,
         1.02536375e+08,  1.02550450e+08,  1.02564525e+08]])